#!/usr/bin/env bash
#
# AdLinkLab one-command production deploy (Ubuntu/Debian, run as root).
#
# Usage:
#   sudo ./deploy.sh                 # uses DOMAIN=adtlab.xyz
#   sudo DOMAIN=example.com ./deploy.sh
#
# What it does:
#   1. Installs Docker + Compose plugin if missing
#   2. Opens 80/443 in ufw (if ufw is active)
#   3. Generates .env with random secrets (kept if it already exists)
#   4. Builds images and starts the full stack (Traefik + Postgres + Redis + API + Worker + Web)
#   5. Runs DB migrations (one-shot) and seeds the demo tenant (idempotent)
#
# Requirements on the server:
#   - Ports 80 and 443 reachable from the internet (provider firewall/security group)
#   - The domain's A record (@ and www) points to this server's public IP
#     (needed for Let's Encrypt HTTP-01 to issue the certificate)
#
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$APP_DIR"

if [ "$(id -u)" -ne 0 ]; then
  echo "Please run as root: sudo ./deploy.sh"
  exit 1
fi

DOMAIN="${DOMAIN:-adtlab.xyz}"
echo "==> Deploying AdLinkLab for domain: ${DOMAIN}"

# --- 1. Docker ---
if ! command -v docker >/dev/null 2>&1; then
  echo "==> Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg openssl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
else
  echo "==> Docker already installed: $(docker --version)"
fi

# --- 2. Firewall ---
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
  echo "==> Opening 80/443 in ufw..."
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
fi

# --- 3. Traefik ACME storage ---
mkdir -p infra/traefik
touch infra/traefik/acme.json
chmod 600 infra/traefik/acme.json

# --- 4. .env with generated secrets ---
if [ ! -f .env ]; then
  echo "==> Generating .env with random secrets..."
  PG_PASS="$(openssl rand -hex 24)"
  PEPPER="$(openssl rand -hex 32)"
  API_KEY="alk_live_$(openssl rand -hex 16)"
  TENANT_ID="00000000-0000-4000-8000-000000000001"
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%FT%TZ). DO NOT COMMIT.
POSTGRES_USER=adlinklab
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=adlinklab
DATABASE_URL=postgresql://adlinklab:${PG_PASS}@postgres:5432/adlinklab
REDIS_URL=redis://redis:6379
ADLINKLAB_API_KEYS=${API_KEY}:${TENANT_ID}
INTEGRATION_TOKEN_PEPPER=${PEPPER}
CORS_ORIGINS=https://${DOMAIN},https://www.${DOMAIN}
ADLINKLAB_API_KEY=${API_KEY}
ADLINKLAB_INTEGRATION_TOKEN=
DOMAIN=${DOMAIN}
ACME_EMAIL=admin@${DOMAIN}
NEXT_PUBLIC_API_BASE_URL=http://api:3001
GOOGLE_ADS_PROVIDER=mock
TRAFFIC_PROVIDER=mock
EOF
  chmod 600 .env
  echo "==> .env created (mode 600)."
else
  echo "==> .env already exists, keeping it."
fi
# Pick up DOMAIN from .env when present, else keep the script default.
ENV_DOMAIN="$(grep -E '^DOMAIN=' .env | cut -d= -f2 || true)"
DOMAIN="${ENV_DOMAIN:-adtlab.xyz}"

# --- 4a. npm registry mirror ---
# registry.npmjs.org is often unreachable/slow from CN/HK servers (ETIMEDOUT
# inside docker build). Pin the mirror idempotently so re-extracting the
# deploy tarball can never drop it.
if ! grep -qE '^registry=' .npmrc 2>/dev/null; then
  echo "==> Using npmmirror registry for pnpm (registry.npmjs.org is unreliable here)..."
  echo 'registry=https://registry.npmmirror.com' >> .npmrc
fi

# --- 4b. Traefik file-provider routers (domain-specific) ---
# The Docker provider is disabled (see docker-compose.yml), so routing lives
# here. Regenerated on every run to stay in sync with DOMAIN.
echo "==> Generating infra/traefik/routers.yml for ${DOMAIN}..."
# Quoted heredoc (<<'EOF'): nothing inside is expanded, so Traefik backticks
# are safe. The domain is injected afterwards via placeholder substitution.
cat > infra/traefik/routers.yml <<'EOF'
# Generated by deploy.sh. DO NOT EDIT MANUALLY.
http:
  routers:
    http-catchall:
      rule: "PathPrefix(`/`) && !PathPrefix(`/.well-known/acme-challenge/`)"
      entryPoints: ["web"]
      middlewares: ["https-redirect@file"]
      service: noop@internal
    api:
      rule: "Host(`__DOMAIN__`) && PathPrefix(`/api`)"
      # Explicit priority: without it Traefik ranks by rule length and the
      # longer web rule (with www host) would steal /api/* requests.
      priority: 100
      entryPoints: ["websecure"]
      tls:
        certResolver: le
      service: api
    web:
      rule: "Host(`__DOMAIN__`) || Host(`www.__DOMAIN__`)"
      priority: 10
      entryPoints: ["websecure"]
      tls:
        certResolver: le
      service: web
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://adlinklab-api:3001"
    web:
      loadBalancer:
        servers:
          - url: "http://adlinklab-web:3000"
EOF
sed -i "s/__DOMAIN__/${DOMAIN}/g" infra/traefik/routers.yml
chmod 644 infra/traefik/routers.yml

# --- 5. Build & start ---
echo "==> Building images and starting the stack (this takes a few minutes)..."
# init.sql is bind-mounted into the postgres container, whose entrypoint reads
# it as the postgres user: it must be world-readable regardless of umask.
chmod 644 infra/postgres/init.sql 2>/dev/null || true
docker compose up --build -d

# --- 6. Wait for API readiness ---
echo "==> Waiting for API to become ready..."
READY=0
for _ in $(seq 1 36); do
  if docker compose exec -T api node -e "fetch('http://127.0.0.1:3001/health/ready').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))" >/dev/null 2>&1; then
    READY=1
    break
  fi
  sleep 10
done
if [ "$READY" -ne 1 ]; then
  echo "WARNING: API did not become ready in time. Check: docker compose logs api"
else
  echo "==> API is ready."
fi

# --- 7. Seed demo tenant (idempotent upserts) ---
echo "==> Seeding demo tenant..."
docker compose run --rm api pnpm --filter @adlinklab/database seed >/dev/null 2>&1 \
  && echo "==> Seed done." \
  || echo "WARNING: seed failed (non-fatal). Run manually: docker compose run --rm api pnpm --filter @adlinklab/database seed"

echo ""
echo "=================================================="
echo " AdLinkLab deployed!"
echo ""
echo "   Web: https://${DOMAIN}"
echo ""
echo "   Containers:"
docker compose ps --format "table {{.Name}}\t{{.Status}}"
echo ""
echo "   Useful commands (run in this directory):"
echo "     docker compose logs -f        # follow logs"
echo "     docker compose ps             # container status"
echo "     docker compose down           # stop everything"
echo "=================================================="
